# logging:
#   config: classpath:log4j2.yml
server:
  port: 9999
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - src/main/webapp
      additional-exclude: static/**, templates/**

  application:
    name: jdbc
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://np.youngatae.shop:3306/post
    username: sample
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: shop.youngatae.member_post.vo
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  swagger-ui:
    path: /swag
  upload:
    path: c:/upload

